"""add filename to files

Revision ID: 985b1c1b30b9
Revises: 
Create Date: 2024-09-05 14:52:59.538540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '985b1c1b30b9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint('uq_file_path', ['path'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('filename')

    # ### end Alembic commands ###
